openapi: 3.0.0
info:
  title: 'Makini API'
  description: 'Makini API'
  contact: developer@eq-centric.com
  version: '0.1'
paths:
  /equipment:
    get:
      summary: 'Display equipment list'
      operationId: EquipmentSearch
      responses:
        '200':
          $ref: '#/components/responses/EquipmentResourceCollection'
  '/equipment/{key}':
    get:
      summary: 'Display the specified resource.'
      operationId: EquipmentGet
      parameters:
        -
          name: key
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/EquipmentResourceItem'
  /parts:
    get:
      summary: 'Display part list'
      operationId: PartSearch
      responses:
        '200':
          $ref: '#/components/responses/PartResourceCollection'
  '/parts/{key}':
    get:
      summary: 'Display the specified resource.'
      operationId: PartGet
      responses:
        '200':
          $ref: '#/components/responses/PartResourceItem'
  /sites:
    get:
      summary: 'Display site list'
      operationId: SiteSearch
      responses:
        '200':
          $ref: '#/components/responses/SiteResourceCollection'
  '/sites/{key}':
    get:
      summary: 'Display the specified resource.'
      operationId: SiteGet
      responses:
        '200':
          $ref: '#/components/responses/SiteResourceItem'
  /work-orders:
    get:
      summary: 'Display work orders list'
      operationId: WorkOrderSearch
      responses:
        '200':
          $ref: '#/components/responses/WorkOrderResourceCollection'
  '/work-orders/{key}':
    get:
      summary: 'Display the specified resource.'
      operationId: WorkOrderGet
      responses:
        '200':
          $ref: '#/components/responses/WorkOrderResourceItem'
components:
  schemas:
    Equipment:
      properties:
        key:
          description: 'Equipment key'
          type: string
        name:
          description: 'Equipment name'
          type: string
        parent_key:
          type: string
        site_key:
          type: string
        active:
          type: boolean
        deactivated:
          type: string
          format: date-time
        category:
          type: string
        is_critical_system:
          type: boolean
        manufacturer:
          type: string
        updated_at:
          type: string
          format: date-time
        serial_number:
          type: string
    Part:
      properties:
        key:
          description: 'Part key'
          type: string
        part_number:
          type: string
        description:
          type: string
        critical_spare:
          type: boolean
        active:
          type: boolean
    PurchaseOrder:
      properties:
        key:
          description: 'Purchase order key'
          type: string
        cost:
          type: string
        description:
          type: string
        due_date:
          type: string
        status:
          type: string
    Site:
      properties:
        key:
          description: 'Site key'
          type: string
        name:
          description: 'Site name'
          type: string
    WorkOrder:
      properties:
        key:
          description: 'Work order key'
          type: string
        equipment_key:
          description: 'Equipment key'
          type: string
        name:
          type: string
        text:
          type: string
        description:
          type: string
        severity:
          type: string
        scheduled_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  responses:
    EquipmentResourceCollection:
      description: 'Equipment list'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Equipment'
    EquipmentResourceItem:
      description: 'Equipment entity'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Equipment'
    PartResourceCollection:
      description: 'Part list'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Part'
    PartResourceItem:
      description: 'Part entity'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Part'
    SiteResourceCollection:
      description: 'Site list'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Site'
    SiteResourceItem:
      description: 'Site entity'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Site'
    WorkOrderResourceCollection:
      description: 'Work order list'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/WorkOrder'
    WorkOrderResourceItem:
      description: 'Work order entity'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WorkOrder'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://api-dev.app.eq-centric.com/link/oauth/authorize'
          scopes: {  }

