openapi: 3.0.0
info:
  title: Makini API
  description: Makini API
  version: '0.1'
  contact:
    name: Roman Kinyakin
    email: roman@makini.io
paths:
  /assets:
    get:
      summary: Display assets list
      operationId: AssetSearch
      responses:
        '200':
          $ref: '#/components/responses/AssetResourceCollection'
    parameters: []
  '/assets/{key}':
    get:
      summary: Display the specified resource.
      operationId: AssetGet
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/AssetResourceItem'
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
  /parts:
    get:
      summary: Display part list
      operationId: PartSearch
      responses:
        '200':
          $ref: '#/components/responses/PartResourceCollection'
  '/parts/{key}':
    get:
      summary: Display the specified resource.
      operationId: PartGet
      responses:
        '200':
          $ref: '#/components/responses/PartResourceItem'
  /sites:
    get:
      summary: Display site list
      operationId: SiteSearch
      responses:
        '200':
          $ref: '#/components/responses/SiteResourceCollection'
  '/sites/{key}':
    get:
      summary: Display the specified resource.
      operationId: SiteGet
      responses:
        '200':
          $ref: '#/components/responses/SiteResourceItem'
  /work-orders:
    get:
      summary: Display work orders list
      operationId: WorkOrderSearch
      responses:
        '200':
          $ref: '#/components/responses/WorkOrderResourceCollection'
  '/work-orders/{key}':
    get:
      summary: Display the specified resource.
      operationId: WorkOrderGet
      responses:
        '200':
          $ref: '#/components/responses/WorkOrderResourceItem'
components:
  schemas:
    Asset:
      title: ''
      type: object
      properties:
        key:
          description: Unique asset identifier
          type: string
        siteKey:
          type: string
          description: 'Identifier of site, which asset belongs to'
        parentKey:
          type: string
          description: Identifier of parent asset if any
        vendorKey:
          type: string
          description: 'Identifier of vendor, from which asset was purchased from'
        modelKey:
          type: string
          description: Identifier of asset model
        teamKey:
          type: string
          description: Identifier of team to which asset is assigned to
        documentKeys:
          type: array
          description: List of identifiers of documents related to asset
          items:
            type: string
        name:
          description: Name of asset
          type: string
        code:
          type: string
          description: 'Identifier of asset in end-users internal taxonomy, e. g. SFI Code or SKU'
        description:
          type: string
          description: Description of asset
        notes:
          type: string
          format: text
          description: Notes to asset in end-user's system
        categoryName:
          type: string
          description: Name of category asset is assigned to
        criticality:
          type: string
          description: Description of asset criticality
        isActive:
          type: boolean
          description: Identifies if asset is currently in use
        manufacturerName:
          type: string
          description: Name of asset manufacturer
        modelName:
          type: string
          description: Name of asset model
        serialNumber:
          type: string
          description: Serial number or barcode
        activatedAt:
          type: string
          format: date-time
          description: Time when asset was activated/enabled
        deactivatedAt:
          type: string
          format: date-time
          description: Time when asset was deactivated/disabled
        createdAt:
          type: string
          format: date-time
          description: Time when entity was created
        updatedAt:
          type: string
          format: date-time
          description: Time when entity was last modified
        deletedAt:
          type: string
          description: Time when entity was deleted/archived
          format: date-time
      required:
        - key
        - siteKey
        - name
        - isActive
        - createdAt
        - updatedAt
    LineItem:
      properties:
        key:
          description: Line item key
          type: string
        purchase_order_key:
          type: string
        entity_key:
          type: string
        entity_type:
          type: string
        storage_key:
          type: string
        description:
          type: string
        quantity:
          type: string
        value:
          type: string
        vendor_key:
          type: string
        delivery_at:
          type: string
        status:
          type: string
        number:
          type: string
        type:
          type: string
    Part:
      type: object
      x-examples: {}
      description: ''
      properties:
        key:
          type: string
          description: Unique team identifier
        siteKeys:
          type: array
          description: 'Identifiers of sites, which part belongs to'
          items:
            type: string
        parentKeys:
          type: string
          description: 'Identifier of assemblies, which part belongs to'
        vendorKeys:
          type: string
          description: 'Identifiers of vendors, supplying the part'
        documentKeys:
          type: array
          description: List of identifiers of documents related to part
          items:
            type: string
        code:
          type: string
          description: 'Identifier of part in end-users internal taxonomy, e. g. SFI Code or SKU'
        isAssembly:
          type: boolean
          description: Identifies if part is an assembly (contains nested parts)
        partNumber:
          type: string
          description: Part number
        name:
          type: string
          description: Name of part
        description:
          type: string
          format: text
          description: Description of part
        notes:
          type: string
          format: text
          description: Notes to part in end-user's system
        criticality:
          type: string
          description: Description of criticality
        isActive:
          type: boolean
          description: Identifies if part is currently in use
        manufacturerName:
          type: string
          description: Name of asset manufacturer
        minimumQuantity:
          type: number
          description: Minimal quanity of part
        uom:
          type: string
          description: Unit of measure
        cost:
          type: number
          description: Cost of purchase
          format: double
        currency:
          type: string
          description: Purchase currency
        createdAt:
          type: string
          description: Time when entity was created
          format: date-time
        updatedAt:
          type: string
          description: Time when entity was last modified
          format: date-time
        deletedAt:
          type: string
          description: Time when entity was deleted/archived
          format: date-time
        inventory:
          type: array
          items: {}
        drawings:
          type: array
          items: {}
      required:
        - key
        - siteKeys
        - isAssembly
        - partNumber
        - name
        - isActive
        - uom
    PurchaseOrder:
      properties:
        key:
          description: Purchase order key
          type: string
        number:
          type: string
        cost:
          type: string
        description:
          type: string
        due_date_at:
          type: string
        vendor_key:
          type: string
        status:
          type: string
    Site:
      type: object
      properties:
        key:
          description: Site key
          type: string
        name:
          description: Site name
          type: string
        lat:
          type: number
          format: double
          description: Site location latitude
        lng:
          type: number
          description: Site location longitude
          format: double
        address:
          type: string
          description: Site address
        properties:
          type: string
          description: 'Key-value map for additional properties, e. g. IMO number'
        notes:
          type: string
          format: text
          description: Notes to asset in end-user's system
        createdAt:
          description: Time when entity was created
          format: date-time
          type: string
        updatedAt:
          type: string
          format: date-time
          description: Time when entity was last modified
        deletedAt:
          type: string
          format: date-time
          description: Time when entity was deleted/archived
      required:
        - key
        - name
        - createdAt
        - updatedAt
    Vendor:
      properties:
        key:
          description: Vendor key
          type: string
        name:
          type: string
        short_name:
          type: string
        active:
          type: string
        vendor_contacts:
          type: array
          items:
            $ref: '#/components/schemas/VendorContact'
        address:
          type: string
        city:
          type: string
        state:
          type: string
        postcode:
          type: string
        country:
          type: string
    VendorContact:
      properties:
        first_name:
          type: string
        middle_name:
          type: string
        last_name:
          type: string
        phone_numbers:
          type: string
        emails:
          type: string
    WorkOrder:
      properties:
        key:
          description: Work order key
          type: string
        equipment_key:
          description: Equipment key
          type: string
        name:
          type: string
        text:
          type: string
        description:
          type: string
        severity:
          type: string
        scheduled_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  responses:
    AssetResourceCollection:
      description: Assets list
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Asset'
    AssetResourceItem:
      description: Asset entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Asset'
    LineItemResourceCollection:
      description: Line Item list
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/LineItem'
    LineItemResourceItem:
      description: Line Item entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LineItem'
    PartResourceCollection:
      description: Part list
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Part'
    PartResourceItem:
      description: Part entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Part'
    SiteResourceCollection:
      description: Site list
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Site'
    SiteResourceItem:
      description: Site entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Site'
    VendorResourceCollection:
      description: Vendor list
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Vendor'
    VendorResourceItem:
      description: Vendor entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Vendor'
    WorkOrderResourceCollection:
      description: Work order list
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/WorkOrder'
    WorkOrderResourceItem:
      description: Work order entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WorkOrder'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.makini.io/link/oauth/authorize'
          tokenUrl: 'https://api.makini.io/link/oauth/token'
          scopes: {}
security:
  - oauth2: []
servers:
  - url: 'https://api.makini.io'
    description: ''
